
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/components/WhatsappButton";
import ScrollProgressCircle from "@/components/ScrollProgressCircle";
import CustomCursor from "@/components/CustomCursor";



const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});




export const metadata: Metadata = {
  title: "BZ Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
      <body className={`${plusJakarta.className} antialiased`}>
            {children}
          <CustomCursor />
           <ScrollProgressCircle />
           <WhatsAppButton />
         

      </body>
    </html>
  );
}