
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/src/components/WhatsappButton";
import ScrollProgressCircle from "@/src/components/ScrollProgressCircle";
import CustomCursor from "@/src/components/CustomCursor";
import { ThemeProvider } from "@/src/components/ThemeProvider";



const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});




export const metadata: Metadata = {
  title: "BZ Analytics - Transform Digitally with Our Technology and IT Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en"suppressHydrationWarning>
      <body className={`${plusJakarta.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
            {children}
            </ThemeProvider>
          <CustomCursor />
           <ScrollProgressCircle />
           <WhatsAppButton />
         

      </body>
    </html>
  );
}